### ISSUE TITLE
Start release counting at 1

### ISSUE THREAD

**Issue by tayapski** [casmith/release-it-calver-plugin#28]
Hi, I've recently just tried out the plugin with the following configuration
```
"release-it": {
    "plugins": {
      "@csmith/release-it-calver-plugin": {
        "format": "yyyy.mm.minor",
        "increment": "calendar.minor"
      }
    }
}
```

Is there possible configuration I can use so that minor starts at 1 instead of zero (0)?

**Comment by casmith** [comment]
If calver supports it, this plugin would be able to as well. I suggest voting for the PR mentioned above.

**Comment by imgrant** [comment]
Sadly I have two PRs open with [node-calver](https://github.com/muratgozel/node-calver/pulls), neither of which seem to have received any attention from the author. I don't think the project is dead, and due to its nature, there's plenty of downstream projects that make use of it. Perhaps a nudge from more people might help, please do add your voice there @tayapski
